services:
  - type: web
    name: arnold-katumba
    runtime: static
    plan: free
    branch: master
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "24.14.1"
      - key: SKIP_INSTALL_DEPS
        value: "true"
